//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w_client.OperationChangesRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="changes", Namespace="http://schemas.datacontract.org/2004/07/WcfService_")]
    [System.SerializableAttribute()]
    public partial class changes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_personField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDs_privchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDs_privgrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middle_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_privField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_group {
            get {
                return this.ID_groupField;
            }
            set {
                if ((this.ID_groupField.Equals(value) != true)) {
                    this.ID_groupField = value;
                    this.RaisePropertyChanged("ID_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_person {
            get {
                return this.ID_personField;
            }
            set {
                if ((this.ID_personField.Equals(value) != true)) {
                    this.ID_personField = value;
                    this.RaisePropertyChanged("ID_person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDs_privch {
            get {
                return this.IDs_privchField;
            }
            set {
                if ((object.ReferenceEquals(this.IDs_privchField, value) != true)) {
                    this.IDs_privchField = value;
                    this.RaisePropertyChanged("IDs_privch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDs_privgr {
            get {
                return this.IDs_privgrField;
            }
            set {
                if ((object.ReferenceEquals(this.IDs_privgrField, value) != true)) {
                    this.IDs_privgrField = value;
                    this.RaisePropertyChanged("IDs_privgr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middle_name {
            get {
                return this.middle_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.middle_nameField, value) != true)) {
                    this.middle_nameField = value;
                    this.RaisePropertyChanged("middle_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_group {
            get {
                return this.name_groupField;
            }
            set {
                if ((object.ReferenceEquals(this.name_groupField, value) != true)) {
                    this.name_groupField = value;
                    this.RaisePropertyChanged("name_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_priv {
            get {
                return this.name_privField;
            }
            set {
                if ((object.ReferenceEquals(this.name_privField, value) != true)) {
                    this.name_privField = value;
                    this.RaisePropertyChanged("name_priv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group_", Namespace="http://schemas.datacontract.org/2004/07/WcfService_")]
    [System.SerializableAttribute()]
    public partial class Group_ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_group {
            get {
                return this.ID_groupField;
            }
            set {
                if ((this.ID_groupField.Equals(value) != true)) {
                    this.ID_groupField = value;
                    this.RaisePropertyChanged("ID_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Privilege", Namespace="http://schemas.datacontract.org/2004/07/WcfService_")]
    [System.SerializableAttribute()]
    public partial class Privilege : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_privilegeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_funcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_privilege {
            get {
                return this.ID_privilegeField;
            }
            set {
                if ((this.ID_privilegeField.Equals(value) != true)) {
                    this.ID_privilegeField = value;
                    this.RaisePropertyChanged("ID_privilege");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_func {
            get {
                return this.name_funcField;
            }
            set {
                if ((object.ReferenceEquals(this.name_funcField, value) != true)) {
                    this.name_funcField = value;
                    this.RaisePropertyChanged("name_func");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group_Privileges", Namespace="http://schemas.datacontract.org/2004/07/WcfService_")]
    [System.SerializableAttribute()]
    public partial class Group_Privileges : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Groups_ID_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Privileges_ID_privilegeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Groups_ID_group {
            get {
                return this.Groups_ID_groupField;
            }
            set {
                if ((this.Groups_ID_groupField.Equals(value) != true)) {
                    this.Groups_ID_groupField = value;
                    this.RaisePropertyChanged("Groups_ID_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Privileges_ID_privilege {
            get {
                return this.Privileges_ID_privilegeField;
            }
            set {
                if ((this.Privileges_ID_privilegeField.Equals(value) != true)) {
                    this.Privileges_ID_privilegeField = value;
                    this.RaisePropertyChanged("Privileges_ID_privilege");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persons_Privileges", Namespace="http://schemas.datacontract.org/2004/07/WcfService_")]
    [System.SerializableAttribute()]
    public partial class Persons_Privileges : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Persons_ID_personField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Privileges_ID_privilegeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Persons_ID_person {
            get {
                return this.Persons_ID_personField;
            }
            set {
                if ((this.Persons_ID_personField.Equals(value) != true)) {
                    this.Persons_ID_personField = value;
                    this.RaisePropertyChanged("Persons_ID_person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Privileges_ID_privilege {
            get {
                return this.Privileges_ID_privilegeField;
            }
            set {
                if ((this.Privileges_ID_privilegeField.Equals(value) != true)) {
                    this.Privileges_ID_privilegeField = value;
                    this.RaisePropertyChanged("Privileges_ID_privilege");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WcfService_")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Groups_ID_GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_personField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WasDelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middle_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Groups_ID_Group {
            get {
                return this.Groups_ID_GroupField;
            }
            set {
                if ((this.Groups_ID_GroupField.Equals(value) != true)) {
                    this.Groups_ID_GroupField = value;
                    this.RaisePropertyChanged("Groups_ID_Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_person {
            get {
                return this.ID_personField;
            }
            set {
                if ((this.ID_personField.Equals(value) != true)) {
                    this.ID_personField = value;
                    this.RaisePropertyChanged("ID_person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WasDel {
            get {
                return this.WasDelField;
            }
            set {
                if ((this.WasDelField.Equals(value) != true)) {
                    this.WasDelField = value;
                    this.RaisePropertyChanged("WasDel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middle_name {
            get {
                return this.middle_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.middle_nameField, value) != true)) {
                    this.middle_nameField = value;
                    this.RaisePropertyChanged("middle_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationChangesRef.IOperationChanges")]
    public interface IOperationChanges {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/add_priv", ReplyAction="http://tempuri.org/IOperationChanges/add_privResponse")]
        int add_priv(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/add_priv", ReplyAction="http://tempuri.org/IOperationChanges/add_privResponse")]
        System.Threading.Tasks.Task<int> add_privAsync(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/GetList", ReplyAction="http://tempuri.org/IOperationChanges/GetListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(w_client.OperationChangesRef.changes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(w_client.OperationChangesRef.Group_))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(w_client.OperationChangesRef.Privilege))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(w_client.OperationChangesRef.Group_Privileges))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(w_client.OperationChangesRef.Persons_Privileges))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(w_client.OperationChangesRef.Person))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetList(object ob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/GetList", ReplyAction="http://tempuri.org/IOperationChanges/GetListResponse")]
        System.Threading.Tasks.Task<object[]> GetListAsync(object ob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/add_group", ReplyAction="http://tempuri.org/IOperationChanges/add_groupResponse")]
        int add_group(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/add_group", ReplyAction="http://tempuri.org/IOperationChanges/add_groupResponse")]
        System.Threading.Tasks.Task<int> add_groupAsync(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/add_pers", ReplyAction="http://tempuri.org/IOperationChanges/add_persResponse")]
        int add_pers(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/add_pers", ReplyAction="http://tempuri.org/IOperationChanges/add_persResponse")]
        System.Threading.Tasks.Task<int> add_persAsync(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/update_pers", ReplyAction="http://tempuri.org/IOperationChanges/update_persResponse")]
        int update_pers(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/update_pers", ReplyAction="http://tempuri.org/IOperationChanges/update_persResponse")]
        System.Threading.Tasks.Task<int> update_persAsync(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/update_groups", ReplyAction="http://tempuri.org/IOperationChanges/update_groupsResponse")]
        int update_groups(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/update_groups", ReplyAction="http://tempuri.org/IOperationChanges/update_groupsResponse")]
        System.Threading.Tasks.Task<int> update_groupsAsync(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/update_per_priv", ReplyAction="http://tempuri.org/IOperationChanges/update_per_privResponse")]
        int update_per_priv(w_client.OperationChangesRef.changes ch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationChanges/update_per_priv", ReplyAction="http://tempuri.org/IOperationChanges/update_per_privResponse")]
        System.Threading.Tasks.Task<int> update_per_privAsync(w_client.OperationChangesRef.changes ch);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperationChangesChannel : w_client.OperationChangesRef.IOperationChanges, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationChangesClient : System.ServiceModel.ClientBase<w_client.OperationChangesRef.IOperationChanges>, w_client.OperationChangesRef.IOperationChanges {
        
        public OperationChangesClient() {
        }
        
        public OperationChangesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationChangesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationChangesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationChangesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int add_priv(w_client.OperationChangesRef.changes ch) {
            return base.Channel.add_priv(ch);
        }
        
        public System.Threading.Tasks.Task<int> add_privAsync(w_client.OperationChangesRef.changes ch) {
            return base.Channel.add_privAsync(ch);
        }
        
        public object[] GetList(object ob) {
            return base.Channel.GetList(ob);
        }
        
        public System.Threading.Tasks.Task<object[]> GetListAsync(object ob) {
            return base.Channel.GetListAsync(ob);
        }
        
        public int add_group(w_client.OperationChangesRef.changes ch) {
            return base.Channel.add_group(ch);
        }
        
        public System.Threading.Tasks.Task<int> add_groupAsync(w_client.OperationChangesRef.changes ch) {
            return base.Channel.add_groupAsync(ch);
        }
        
        public int add_pers(w_client.OperationChangesRef.changes ch) {
            return base.Channel.add_pers(ch);
        }
        
        public System.Threading.Tasks.Task<int> add_persAsync(w_client.OperationChangesRef.changes ch) {
            return base.Channel.add_persAsync(ch);
        }
        
        public int update_pers(w_client.OperationChangesRef.changes ch) {
            return base.Channel.update_pers(ch);
        }
        
        public System.Threading.Tasks.Task<int> update_persAsync(w_client.OperationChangesRef.changes ch) {
            return base.Channel.update_persAsync(ch);
        }
        
        public int update_groups(w_client.OperationChangesRef.changes ch) {
            return base.Channel.update_groups(ch);
        }
        
        public System.Threading.Tasks.Task<int> update_groupsAsync(w_client.OperationChangesRef.changes ch) {
            return base.Channel.update_groupsAsync(ch);
        }
        
        public int update_per_priv(w_client.OperationChangesRef.changes ch) {
            return base.Channel.update_per_priv(ch);
        }
        
        public System.Threading.Tasks.Task<int> update_per_privAsync(w_client.OperationChangesRef.changes ch) {
            return base.Channel.update_per_privAsync(ch);
        }
    }
}
